### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by RuedigerMoeller** [simschla/fast-and-simple-minify#2]
Hi, I'd like to grab out your Douglas Crockfort JSMin port class only. Would you mind to add a Apache 2.0 License Header into the file ?
As I want to apply minification dynamically in my Kontraktor 3 spa/actor platform I don't need the ant stuff etc.

kind regards
-ruediger

**Comment by simschla** [comment]
I've added the apache 2.0 License to the repository. So please fell free to use the code.

**Comment by RuedigerMoeller** [comment]
Thanks a lot :-)
